import type {
  ProjectDetailData,
  ProjectCategory,
} from '../components/ProjectDetail';

export type CategoryEntry = {
  id: ProjectCategory;
  title: string;
  image: string;
  blurb: string;
};

const buildGallery = (slug: string, files: string[]) =>
  files.map((f) => `/projects/${slug}/${f}`);

export const CATEGORY_ENTRIES: CategoryEntry[] = [
  {
    id: 'community',
    title: 'Community',
    image: '/projects/community/leyton/01.jpg',
    blurb: 'Civic, public, neighbourhood.',
  },
  {
    id: 'residential',
    title: 'Residential',
    image: '/projects/residential/richmond-house/01.jpeg',
    blurb: 'Houses, apartments, homes.',
  },
  {
    id: 'commercial',
    title: 'Commercial',
    image: '/projects/commercial/qaboli/01.jpg',
    blurb: 'Workspaces, retail, hospitality.',
  },
];

const PLACEHOLDER_DESCRIPTION = 'Full project details coming soon.';
const PLACEHOLDER_LONG_DESCRIPTION =
  'Full project description and photography to follow.';

export const projects: ProjectDetailData[] = [
  // ─── RESIDENTIAL ──────────────────────────────────────────────────────
  {
    title: '57 Castle Street, Reading',
    image: '/projects/residential/57-castle-street-reading/01.webp',
    location: 'Reading, Berkshire',
    year: '',
    scope: 'Residential',
    description: PLACEHOLDER_DESCRIPTION,
    longDescription: PLACEHOLDER_LONG_DESCRIPTION,
    gallery: buildGallery('residential/57-castle-street-reading', [
      '01.webp',
      '02.png',
    ]),
    category: 'residential',
  },
  {
    title: 'Balham',
    image: '/projects/residential/balham/01.png',
    location: 'Balham, London',
    year: '',
    scope: 'Residential',
    description: PLACEHOLDER_DESCRIPTION,
    longDescription: PLACEHOLDER_LONG_DESCRIPTION,
    gallery: buildGallery('residential/balham', ['01.png', '02.png']),
    category: 'residential',
  },
  {
    title: 'Finchley House',
    image: '/projects/residential/finchley-house/01.png',
    location: 'Finchley, London',
    year: '',
    scope: 'Residential',
    description: PLACEHOLDER_DESCRIPTION,
    longDescription: PLACEHOLDER_LONG_DESCRIPTION,
    gallery: buildGallery('residential/finchley-house', [
      '01.png',
      '02.webp',
      '03.webp',
      '04.webp',
    ]),
    category: 'residential',
  },
  {
    title: 'Finsbury Park',
    image: '/projects/residential/finsbury-park/01.jpg',
    location: 'Finsbury Park, London',
    year: '',
    scope: 'Residential',
    description: PLACEHOLDER_DESCRIPTION,
    longDescription: PLACEHOLDER_LONG_DESCRIPTION,
    gallery: buildGallery('residential/finsbury-park', ['01.jpg', '02.jpg']),
    category: 'residential',
  },
  {
    title: 'Hitchen',
    image: '/projects/residential/hitchen/01.jpg',
    location: 'Hitchin, Hertfordshire',
    year: '',
    scope: 'Residential',
    description: PLACEHOLDER_DESCRIPTION,
    longDescription: PLACEHOLDER_LONG_DESCRIPTION,
    gallery: buildGallery('residential/hitchen', [
      '01.jpg',
      '02.jpeg',
      '03.jpeg',
      '04.jpeg',
      '05.jpeg',
      '06.jpeg',
      '07.jpeg',
    ]),
    category: 'residential',
  },
  {
    title: 'Richmond House',
    image: '/projects/residential/richmond-house/01.jpeg',
    location: 'Richmond, London',
    year: '',
    scope: 'Residential',
    description: PLACEHOLDER_DESCRIPTION,
    longDescription: PLACEHOLDER_LONG_DESCRIPTION,
    gallery: buildGallery('residential/richmond-house', [
      '01.jpeg',
      '02.jpeg',
      '03.jpeg',
      '04.jpeg',
      '05.jpeg',
      '06.jpeg',
      '07.jpeg',
      '08.jpeg',
      '09.jpeg',
      '10.jpeg',
      '11.jpeg',
      '12.jpeg',
      '13.jpeg',
      '14.jpeg',
      '15.jpeg',
      '16.jpeg',
      '17.jpeg',
      '18.jpeg',
      '19.jpeg',
    ]),
    category: 'residential',
  },
  {
    title: 'Wembley',
    image: '/projects/residential/wembley/01.png',
    location: 'Wembley, London',
    year: '',
    scope: 'Residential',
    description: PLACEHOLDER_DESCRIPTION,
    longDescription: PLACEHOLDER_LONG_DESCRIPTION,
    gallery: buildGallery('residential/wembley', [
      '01.png',
      '02.png',
      '03.jpg',
      '04.jpg',
      '05.jpg',
      '06.jpg',
      '07.jpg',
      '08.jpg',
      '09.jpg',
      '10.jpg',
      '11.jpg',
    ]),
    category: 'residential',
  },

  // ─── COMMUNITY ────────────────────────────────────────────────────────
  {
    title: 'IDC',
    image: '/projects/community/idc/01.jpg',
    location: 'United Kingdom',
    year: '',
    scope: 'Community',
    description: PLACEHOLDER_DESCRIPTION,
    longDescription: PLACEHOLDER_LONG_DESCRIPTION,
    gallery: buildGallery('community/idc', [
      '01.jpg',
      '02.jpg',
      '03.jpeg',
      '04.jpeg',
      '05.jpeg',
      '06.jpeg',
      '07.jpeg',
      '08.jpeg',
      '09.jpeg',
      '10.jpeg',
      '11.jpeg',
      '12.jpeg',
      '13.jpeg',
      '14.jpeg',
      '15.jpeg',
      '16.jpeg',
      '17.jpeg',
      '18.jpeg',
      '19.jpeg',
      '20.jpeg',
      '21.jpeg',
      '22.jpeg',
      '23.jpeg',
      '24.jpeg',
      '25.jpeg',
      '26.jpeg',
    ]),
    category: 'community',
  },
  {
    title: 'Leyton',
    image: '/projects/community/leyton/01.jpg',
    location: 'Leyton, London',
    year: '',
    scope: 'Community',
    description: PLACEHOLDER_DESCRIPTION,
    longDescription: PLACEHOLDER_LONG_DESCRIPTION,
    gallery: buildGallery(
      'community/leyton',
      Array.from({ length: 40 }, (_, i) =>
        `${String(i + 1).padStart(2, '0')}.jpg`
      )
    ),
    category: 'community',
  },
  {
    title: 'Luton',
    image: '/projects/community/luton/01.jpg',
    location: 'Luton, Bedfordshire',
    year: '',
    scope: 'Community',
    description: PLACEHOLDER_DESCRIPTION,
    longDescription: PLACEHOLDER_LONG_DESCRIPTION,
    gallery: buildGallery('community/luton', [
      '01.jpg',
      '02.jpg',
      '03.jpg',
      '04.jpg',
      '05.jpg',
      '06.jpg',
      '07.jpg',
    ]),
    category: 'community',
  },
  {
    title: 'Luton Central',
    image: '/projects/community/luton-central/01.webp',
    location: 'Luton, Bedfordshire',
    year: '',
    scope: 'Community',
    description: PLACEHOLDER_DESCRIPTION,
    longDescription: PLACEHOLDER_LONG_DESCRIPTION,
    gallery: buildGallery('community/luton-central', ['01.webp']),
    category: 'community',
  },
  {
    title: 'Southall Washrooms',
    image: '/projects/community/southall-washrooms/01.webp',
    location: 'Southall, London',
    year: '',
    scope: 'Community',
    description: PLACEHOLDER_DESCRIPTION,
    longDescription: PLACEHOLDER_LONG_DESCRIPTION,
    gallery: buildGallery('community/southall-washrooms', [
      '01.webp',
      '02.jpeg',
      '03.jpeg',
      '04.jpeg',
    ]),
    category: 'community',
  },

  // ─── COMMERCIAL ───────────────────────────────────────────────────────
  {
    title: 'Qaboli',
    image: '/projects/commercial/qaboli/01.jpg',
    location: 'United Kingdom',
    year: '',
    scope: 'Commercial',
    description: PLACEHOLDER_DESCRIPTION,
    longDescription: PLACEHOLDER_LONG_DESCRIPTION,
    gallery: buildGallery('commercial/qaboli', ['01.jpg', '02.jpg', '03.jpg']),
    category: 'commercial',
  },
];
